# Flux through the first distance interface.
input = "../input"
ncpus = 1

pairs = [
  [20, 71],
]

# Hybrid OP:
# Q is distance-based while no listed pair is bonded.
# If use_bonds = true and one or more listed pairs are bonded, Q = nbonds.
distance_thresholds = [8, 5, 3, 2]
distance_final_state = 0

use_bonds = true
bond_threshold = -0.10

initial_seed = 12345
desired_success_count = 10

state_A = -4
interface = [-4, -3]

[log]
filename = "ffs.log"
verbose = true
also_stderr = true
