CC=mpicxxintel
SINGLECC = c++
FLAGS= -lgsl -lgslcblas -O3 -DHAVE_MPI -ipo
SINGLEFLAGS= -lgsl -lgslcblas -O3  
LIBS= -L/usr/local/shared/gsl-1.12/lib 
INC=  -I/usr/local/shared/gsl-1.12/include
SRC= anneal.cpp pars.cpp fits.cpp
DEBUGFLAGS= -lgsl -lgslcblas -g -DDBG

simulation: anneal.cpp main.cpp pars.cpp pars.h anneal.h fits.h fits.cpp
	$(CC) -o simulation $(SRC) main.cpp  $(INC) $(LIBS) $(FLAGS) 

Rsimulation: anneal.cpp main_test_not.cpp pars.cpp pars.h anneal.h fits.h fits.cpp
	$(SINGLECC) -o Rsimulation $(SRC) main_test_not.cpp  $(INC) $(LIBS) $(SINGLEFLAGS) 

debug: anneal.cpp main_test_not.cpp pars.cpp pars.h anneal.h fits.h fits.cpp
	$(SINGLECC) -o Debug $(SRC) main_test_not.cpp  $(INC) $(LIBS) $(DEBUGFLAGS) 

rethermsimulation: anneal.cpp main.cpp pars.cpp pars.h anneal.h fits.h fits.cpp
	$(CC) -o rethermsimulation $(SRC) main_retherm.cpp  $(INC) $(LIBS) $(FLAGS) 
test: anneal.cpp main_test.cpp pars.cpp pars.h anneal.h fits.h fits.cpp
	$(CC) -o test $(SRC) main_test.cpp  $(INC) $(LIBS) $(FLAGS) 
singletest: anneal.cpp main_test.cpp pars.cpp pars.h anneal.h fits.h fits.cpp
	$(SINGLECC) -o singletest $(SRC) main_test.cpp  $(INC) $(LIBS) $(SINGLEFLAGS) 

